### ISSUE TITLE
QUESTION: Using plugins with the gulp task?

### ISSUE THREAD

**Issue by caraya** [mcecot/gulp-markdown-it#4]
I'm using the following task. 

```javascript
gulp.task('markdown', function() {
  gulp.src('./src/md-content/*.md')
    .pipe(markdown({
      preset: 'commonmark',
      xhtmlOut: true,
      linkify: true,
      typographer: true,
      plugins: [ MARKDOWNIT_PLUGINS ]
    }))
    .pipe(gulp.dest("./src/html-content"));
});
```
MARKDOWN_PLUGINS is a variable that contains all the plugins I want to use

```javascript
const MARKDOWNIT_PLUGINS = [
  'markdown-it-anchor',
  'markdown-it-table-of-contents',
  'fa-tool',
  'markdown-it-attrs',
  'markdown-it-abbr',
  'markdown-it-task-lists',
  'markdown-it-implicit-figures',
  'markdown-it-kbd',
  'markdown-it-footnote',
  'markdown-it-block-embed',
  'markdown-it-prism',
  'markdown-it-katex'
];
```

The task runs successfully but none of the plugins seems to be running. I can't get the expected results from the plugins. Implicit figures doesn't render as expected among other issues I'm finding. 

Am I using the plugins correctly? If not what should I use to get these plugins working?

**Comment by tom-wolfe** [comment]
I know this is 9 months too late, but in case anybody else has the same problem, in your code, the variable `MARKDOWNIT_PLUGINS` is already an array. Passing it as `plugins: [ MARKDOWNIT_PLUGINS ]` just nests that array inside another one. You should use `plugins: MARKDOWNIT_PLUGINS` instead.

**Comment by caraya** [comment]
THank, I knew it was a simple fix, just couldn't figure it out 💯

**Comment by caraya** [comment]
I reinstalled everything, reinstalled markdown-it, reinstalled the plugins, made sure that the code references the array without nesting and now I get the following error

```
[16:35:57] TypeError: plugin.apply is not a function
    at MarkdownIt.use (/Users/carlos/code/starter/node_modules/gulp-markdown-it/node_modules/markdown-it/lib/index.js:470:10)
    at markdownItPlugin (/Users/carlos/code/starter/node_modules/gulp-markdown-it/index.js:30:10)
    at Gulp.gulp.task (/Users/carlos/code/starter/gulpfile.js:86:11)
    at module.exports (/Users/carlos/code/starter/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/carlos/code/starter/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/carlos/code/starter/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/carlos/code/starter/node_modules/orchestrator/index.js:134:8)
    at Gulp.<anonymous> (/Users/carlos/code/starter/node_modules/gulp/index.js:36:18)
    at Gaze.<anonymous> (/Users/carlos/code/starter/node_modules/glob-watcher/index.js:18:14)
    at emitTwo (events.js:106:13)
    at Gaze.emit (events.js:191:7)
    at Gaze.emit (/Users/carlos/code/starter/node_modules/gaze/lib/gaze.js:129:32)
    at /Users/carlos/code/starter/node_modules/gaze/lib/gaze.js:415:16
    at StatWatcher._pollers.(anonymous function) (/Users/carlos/code/starter/node_modules/gaze/lib/gaze.js:326:7)
    at emitTwo (events.js:106:13)
    at StatWatcher.emit (events.js:191:7)
    at StatWatcher._handle.onchange (fs.js:1501:10)
```

**Comment by tom-wolfe** [comment]
Looking at the stack trace, that's an issue with one of the plugins you're using.

I'd recommend disabling the plugins, then re-enabling them one-by-one until it breaks so you can figure out which one. It's also worth checking the versions of each plugin you're using.

I searched the error message and found [this issue](https://github.com/valeriangalliat/markdown-it-anchor/issues/12) referenced in the markdown-it-anchor plugin, so maybe try to disable that one first. If not, it could be one of the other plugins has the same or similar bug.

**Comment by caraya** [comment]
Again, thanks for your help. Removing the plugin solved the problem. 

The version installed via NPM is ancient. I've asked in the issue if the plugin is still being released in NPM or not. 

There are other issues with gulp-markdown-it. It uses markdown-it 4.x instead of the current 8.x. I may have to revert back to remarkable if it continues being an issue.

**Comment by tom-wolfe** [comment]
No worries! Glad to be of assistance.

As you've had no response from the author, I feel less guilty pointing you toward my own gulp task for markdown-it: https://github.com/trwolfe13/gulp-markdownit. I made it after I couldn't get this one to work as I needed.

It functions almost the same as this one, with the difference that it doesn't rely on a specific version of markdown-it, and allows more control over plugin initialisation.
